#if !canImport(ObjectiveC)
import XCTest

extension ClockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClockTests = [
        ("testMonotonicClock", testMonotonicClock),
        ("testProcessClock", testProcessClock),
        ("testRealtimeClock", testRealtimeClock),
        ("testThreadClock", testThreadClock),
    ]
}

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testDistantFuture", testDistantFuture),
        ("testDistantPast", testDistantPast),
        ("testDoubleConversion", testDoubleConversion),
        ("testIntegerConversion", testIntegerConversion),
        ("testStringConversion", testStringConversion),
        ("testTimeoutArithmetic", testTimeoutArithmetic),
        ("testView", testView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ClockTests.__allTests__ClockTests),
        testCase(TimeTests.__allTests__TimeTests),
    ]
}
#endif
